source_path = "data_files/CANOE/optGap_2024-09-21/" # string
target_path = "data_files/CANOE/optGap_2024-09-21/outputs/" # string

# toggle to determine whether all files are in form (#)days.sqlite, where # is one of the integers in days
# If True, expects numbers in days array
# If false, expects custom names in files array
simple_db_names = True

# Set number of rep days for simple db names
# Must be ordered in increasing # of days
days = [8, 10, 12, 16, 20, 24]

# If not using custom names, set to False as a filler value
# Must be ordered in increasing # of days
custom_db_names = False
